packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

source "googlecompute" "autogenerated_1" {
  credentials_file    = "credentials.json"
  image_family        = "custom-centos-stream-8"
  image_name          = "custom-centos-stream-8"
  network             = "default"
  project_id          = "csye6225-414414"
  source_image_family = "centos-stream-8"
  ssh_username        = "centos"
  zone                = "us-central1-a"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    script = "appsetup.sh"
  }

  provisioner "file" {
    source      = "webapp.zip"
    destination = "webapp.zip"
  }

  provisioner "shell" {
    inline = [
      "sudo dnf install -y unzip",
      "unzip webapp.zip -d webapp"
    ]
  }
}
